<a href="https://colab.research.google.com/github/jo-soobin/crawling_study/blob/master/2_2_%EC%A0%95%EC%A0%81%ED%81%AC%EB%A1%A4%EB%A7%81(%EC%A7%80%EC%8B%9Din%EC%98%88%EC%A0%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
import datetime as dt

url = 'https://kin.naver.com/search/list.naver?query=%EB%A1%9C%EB%98%90%EB%8B%B9%EC%B2%A8%EB%90%98%EB%A9%B4'
html = requests.get(url)
soup = bs(html.text, 'html.parser')
df = pd.DataFrame(columns=['순서',"제목", "날짜"])
#s_content > div.section > ul
titles = soup.select('#s_content > div.section > ul')
title = titles[0].find_all('li')
num = len(title)
ranking=0

for i in range(num):
  date = pd.to_datetime(title[i].find('dd').text) 
  subject = (title[i].find('dt').text)
  ranking+=1
  df = df.append({'순서':ranking,'제목':subject.replace('\n',''),'날짜':date},ignore_index = True)

In [41]:
df

   순서                       제목         날짜
0   1       로또 1018회 예상번호 당첨번호 2022-06-04
1   2      로또 당첨되는 꿈 꾸면 좋은건가요? 2022-07-22
2   3                    로또 당첨 2022-07-24
3   4     로또 43억 당첨 5게임 되면 실수령 2022-07-08
4   5               로또 당첨시 수령인 2022-07-05
5   6           로또 같은회차 가족동시당첨 2022-07-20
6   7        해외로또 당첨시 받기 힘든이유? 2022-07-04
7   8         로또복권당첨시 당첨금 수령방법 2022-07-05
8   9  로또당첨1등 되면 농협본점이 아니라...  2022-05-07
9  10        로또 당첨꿈 꿨어요 로또사볼까요 2022-02-13

In [45]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
url = "https://kin.naver.com/search/list.naver?query=%EA%B2%B0%ED%98%BC%ED%95%98%EB%8A%94%EB%B0%A9%EB%B2%95"

html = requests.get(url)
soup = bs(html.text, "html.parser")

# selector 를 이용한 태그 검색
titles = soup.select("#s_content > div.section > ul")
title = titles[0].find_all("li")


df = pd.DataFrame(columns=["제목", "등록일","내용"])
for li in title:
  df = df.append({"등록일":li.find_all("dd")[0].text, "제목":li.find("dt").text.replace("\n",""),"내용":li.find_all("dd")[1].text}, ignore_index=True)

In [46]:
df

,제목,등록일,내용
0,결혼하는방법,2022.06.09.,... 저랑 결혼을 할려면 어떻게 해야되나요? 기한 넘기지 말고... 현지 혼인신...
1,연예인이랑 결혼하는방법,2022.06.25.,연예인이랑 결혼 하고싶은 한 여자 입니다 연예인이랑 결혼하려면 무조건 학력은... ...
2,불법체류자 태국인과 결혼하는 방법이있...,2022.05.31.,불법체류자 태국인과 결혼하는 방법이있나요? 여성분은 3년이상 불법체류하고있는 상태이...
3,이도현 배우랑 결혼하는방법,2022.01.13.,이도현 배우랑 결혼하는 방법 알려주세요. 나이는 10살 정도 차이나구요. 이도현씨를...
4,여친이랑 결혼하는방법?,2022.02.10.,안녕하세요 제목 그대로 저는 지적장애인이고 30대 초반남이고 여친도 지적장애인 30...
5,국제결혼방법,2022.02.01.,우즈백 남자친구하고 결혼준비하고 있어요 빨리결혼하는 방법좀가르쳐주세요 참고로 우즈백...
6,손석구랑 결혼하는 방법,2022.06.27.,안녕하세요 고등학생입니다 제가 손석구가 너무너무너무넘눠무넘 좋아요 그래서 결혼을 해...
7,범규랑 결혼하는 방법,2022.02.23.,아니 투바투범규랑 결혼하는 방법 좀 알려주세요 아니 진짜 446일차 모아인데요 진짜...
8,긴급) 좋아하는오빠랑 결혼하는방법,2021.10.29.,좋아하는오빠랑 결혼하는 방법 좀 알려주세요. 진짜 제 소원인데 결혼할 수 있을까요?...
9,연애와 결혼을 하지 않고 혼자 사는 방법...,2022.06.23.,... 연애와 결혼을 하지 않고 혼자 사는 방법에 대해 궁금한 점이 있어서 질문드립...